version: "3.9"
services:
  postgres:
    container_name: keycloak_db
    image: "postgres:latest"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: keycloak
      POSTGRES_HOST: postgres
    networks:
      - local
    ports:
      - "5432:5432"

  keycloak:
    container_name: keycloak
    build:
      context: .
      args:
        KEYCLOAK_VERSION: latest
    command: ['start', '--optimized']
    environment:
      JAVA_OPTS_APPEND: -Dkeycloak.profile.feature.upload_scripts=enabled
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: root                      # postgres user
      KC_DB_PASSWORD: postgres_password         # postgres password
      KC_HEALTH_ENABLED: 'true'
      KC_HTTP_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KC_PROXY: edge
      KEYCLOAK_ADMIN: admin                    # keycloak admin
      KEYCLOAK_ADMIN_PASSWORD: Aa123456789*-+  # keycloak password
      KC_HOSTNAME_STRICT: false
      KC_HTTPS_KEY_STORE_FILE: /etc/x509/https/tls.pfx
      KC_HTTPS_KEY_STORE_PASSWORD: 1234
    ports:
      - "2008:8080"
      - "2009:8443" # SSL
    depends_on:
      - postgres
    volumes:
      - keycloak_data_cert:/etc/x509/https
      - ./certs/aspnetapp.pfx:/etc/x509/https/tls.pfx
    networks:
      - local

networks:
  local:
    name: local
    driver: bridge

volumes:
  postgres_data:
  keycloak_data_cert:

